name: main
on:
  push:
    branches:
      - main
jobs:
  test-and-release:
    runs-on: ubuntu-24.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v5

      - name: Set up Node.js 🚀
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Run Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          # if there is no gold image to compare a screenshot to
          # it is a problem, and we should fail the tests
          env: failOnMissingGoldImage=true

      - name: Check types 🏷️
        run: npm run lint

      # after the test run completes store the screenshots and diffs
      - name: Save screenshots 📸
        uses: actions/upload-artifact@v4
        # always upload the screenshots, even if the tests fail
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Semantic Release 🚀
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
